---

- name: Setup RedHat Repositories
  hosts: all
  roles:
   - { role: repo-config }
  tags:
    - setup-repos

- name: Setup HAProxy
  hosts: frontends
  roles:
   - { role: haproxy }
  tags:
    - setup-haproxy

- name: Setup HTTP and Tomcat
  hosts: apps
  roles:
   - { role: http-tomcat }
  tags:
    - setup-tomcat

- name: Setup application1 
  hosts: apps1
  roles:
   - { role: application1 }

- name: Setup application2 
  hosts: apps2
  roles:
   - { role: application2 }

- name: Setup postgresql
  hosts: appsdb
  roles:
   - { role: postgresql }
  tags:
    - setup-postgresql